[project]
name = "time-think"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mypy>=1.8.0",
    "pre-commit>=4.2.0",
    "pydantic>=2.12.2",
    "pytest==8.4.1",
]

[dependency-groups]
dev = ["ruff>=0.11.10"]
